---
abstract: 'Email address validation type constraint for Moose.'
author:
  - 'Tomas Doran (t0m) C<< <bobtfish@bobtfish.net> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0
  namespace::autoclean: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types-Email
no_index:
  directory:
    - inc
    - t
requires:
  Email::Valid: 0
  Moose: 0
  MooseX::Types::Common: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bobtfish/moosex-types-email/tree/master
version: 0.002
